name: CD

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to checkout."
        type: string
        default: "v1.20.1"

env:
  GCC_VERSION: 11
  CMAKE_VERSION: 3.26
  PYTHON_VERSION: 3.9
  NODE_VERSION: 20

defaults:
  run:
    shell: bash

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Clone onnxruntime
        uses: actions/checkout@v4
        with:
          repository: "microsoft/onnxruntime"
          ref: ${{ github.event.inputs.ref }}

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ env.GCC_VERSION }}

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ env.CMAKE_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Continue on error because final steps might fail while library is already built.
      - name: Run debug build
        continue-on-error: true
        run: |
          ./build.sh \
          --build_dir ./build \
          --config Debug \
          --build_wasm_static_lib \
          --enable_wasm_simd \
          --enable_wasm_threads \
          --skip_tests \
          --disable_rtti \
          --use_webgpu \
          --parallel

      - name: Rename library
        continue-on-error: true
        run: mv build/Debug/libonnxruntime_webassembly.a build/Debug/libonnxruntime.a

      - name: Run release build
        continue-on-error: true
        run: |
          ./build.sh \
          --build_dir ./build \
          --config Release \
          --build_wasm_static_lib \
          --enable_wasm_simd \
          --enable_wasm_threads \
          --skip_tests \
          --disable_wasm_exception_catching \
          --disable_rtti \
          --use_webgpu \
          --parallel

      - name: Rename library
        continue-on-error: true
        run: mv build/Release/libonnxruntime_webassembly.a build/Release/libonnxruntime.a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libonnxruntime-${{ github.event.inputs.ref }}-wasm
          path: |
            build/Debug/libonnxruntime.a
            build/Release/libonnxruntime.a
            build/Debug/libonnxruntime_xnnpack.a
            build/Release/libonnxruntime_xnnpack.a
